// Shared HTML fragments for the OAuth login templates. Login is the only
// generated public HTML; marketing pages are gone. Nothing here is escaped
// against untrusted input — callers pass developer-authored constants.

import type { SiteLocale } from "../src/routes.js";
import { chromeFor } from "../src/copy/chrome.js";

/** Minimal HTML-entity escaping for text interpolated into element bodies. */
export function esc(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export const HEAD_ASSETS = `        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link rel="preconnect" href="https://cdn.jsdelivr.net" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,400..800&family=Instrument+Sans:ital,wght@0,400..700;1,400..700&family=Geist+Mono:wght@400;500&display=swap"
            rel="stylesheet"
        />
        <link
            rel="stylesheet"
            href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@7.2.0/css/all.min.css"
        />
        <link rel="stylesheet" href="/styles.css" />
        <script
            async
            src="https://www.googletagmanager.com/gtag/js?id=G-1K4HRB2R8X"
        ></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() {
                dataLayer.push(arguments);
            }
            gtag("js", new Date());
            gtag("config", "G-1K4HRB2R8X");
        </script>`;

export const THEME_PREPAINT = `        <script>
            // Apply a saved theme override before paint to avoid a flash.
            (function () {
                try {
                    var t = localStorage.getItem("theme");
                    if (t === "dark" || t === "light")
                        document.body.setAttribute("data-theme", t);
                } catch (e) {}
            })();
        </script>`;

export const SITE_SCRIPT = `        <script src="/site.js" defer></script>`;

export function generatedBanner(script: string): string {
    return `        <!-- Generated by ${script} — edit the data there, not this file. -->`;
}

/**
 * Login header. Brand stays on this page (`#main`); it must not send anyone
 * to `/`, which is not HTML. Language switcher is `{{LANG_SWITCHER}}` so
 * oauth.ts can stamp authorizeUrl() links for the in-flight session.
 */
export function nav(locale: SiteLocale): string {
    const c = chromeFor(locale);
    return `        <a class="skip" href="#main">${esc(c.skipToContent)}</a>
        <header class="site-head" id="site-head">
            <div class="head-inner">
                <a class="brand" href="#main" aria-label="${esc(c.brandHomeAriaLabel)}">
                    <span class="brand-mark" aria-hidden="true">🍏</span>
                    <span>Nutrition&nbsp;MCP</span>
                </a>
                <div class="head-tools">
                    {{LANG_SWITCHER}}
                    <details class="theme-switch" id="theme-switch">
                        <summary
                            class="icon-btn"
                            aria-label="${esc(c.theme.ariaLabel)}"
                            title="${esc(c.theme.title)}"
                        >
                            <svg class="auto" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                                <circle cx="12" cy="12" r="9" />
                                <path d="M12 3a9 9 0 0 0 0 18z" fill="currentColor" stroke="none" />
                            </svg>
                            <svg class="moon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                                <path d="M21 12.8A9 9 0 1 1 11.2 3a7 7 0 0 0 9.8 9.8z" />
                            </svg>
                            <svg class="sun" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">
                                <circle cx="12" cy="12" r="4" />
                                <path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4" />
                            </svg>
                        </summary>
                        <div class="theme-menu" role="group" aria-label="${esc(c.theme.title)}">
                            <button type="button" data-theme-set="system" aria-pressed="true">${esc(c.theme.system)}</button>
                            <button type="button" data-theme-set="light" aria-pressed="false">${esc(c.theme.light)}</button>
                            <button type="button" data-theme-set="dark" aria-pressed="false">${esc(c.theme.dark)}</button>
                        </div>
                    </details>
                </div>
            </div>
        </header>`;
}

export function footer(locale: SiteLocale): string {
    const c = chromeFor(locale);
    return `        <footer class="footer">
            <div class="footer-inner">
                <span class="footer-brand">
                    <span class="brand-mark" aria-hidden="true">🍏</span>
                    Nutrition MCP
                </span>
                <p class="footer-note">
                    ${esc(c.footer.note)}
                </p>
            </div>
        </footer>`;
}
