// Shared HTML fragments for the OAuth login template (scripts/gen-login.ts).
// Login is the only generated public HTML and is styled by /app.css, the same
// stylesheet as the household app. Nothing here is escaped against untrusted
// input — callers pass developer-authored constants.

/** Minimal HTML-entity escaping for text interpolated into element bodies. */
export function esc(s: string): string {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

export function generatedBanner(script: string): string {
    return `        <!-- Generated by ${script} — edit the data there, not this file. -->`;
}
